# NextCloud Ansible Inventory
# Lab nodes managed from the orchestrator

[nextcloud]
fnet2 ansible_host=192.168.0.142 ansible_user=friasc

[lab:children]
nextcloud

[lab:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o ConnectTimeout=5