#!/usr/bin/env python3
"""
routing_dashboard.py — Weekly Performance Dashboard for TI-011 Meta-Orchestration
Generates a markdown report from routing decision logs.

Usage:
    python3 routing_dashboard.py --weekly
    python3 routing_dashboard.py --weekly --save
"""

import json
import argparse
from pathlib import Path
from datetime import datetime, timedelta

REPO_ROOT = Path(__file__).resolve().parents[2]
SESSIONS_DIR = REPO_ROOT / "technical-infrastructure" / "wiki" / "operational" / "sessions"
STATUS_DIR = REPO_ROOT / "technical-infrastructure" / "wiki" / "operational" / "status"
JSONL_FILE = SESSIONS_DIR / "model-routing-decisions.jsonl"


def load_logs(days=7):
    if not JSONL_FILE.exists():
        return []
    cutoff = datetime.now() - timedelta(days=days)
    logs = []
    with open(JSONL_FILE) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
                ts = datetime.fromisoformat(entry.get("timestamp", "1970-01-01T00:00:00"))
                if ts >= cutoff:
                    logs.append(entry)
            except (json.JSONDecodeError, ValueError):
                continue
    return logs


def generate_report(logs):
    if not logs:
        return "# Routing Dashboard\n\nNo logs yet. Run prompts through classify_prompt.py --route to generate data."
    
    lines = ["# TI-011 Routing Dashboard", f"Period: Last 7 days | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ""]
    
    # Summary stats
    total = len(logs)
    local = sum(1 for e in logs if e.get("provider") == "ollama")
    cloud = total - local
    avg_latency = sum(e.get("latency_ms", 0) for e in logs) / total if total else 0
    total_cost = sum(e.get("cost", 0) for e in logs)
    
    lines.append("## Summary")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total prompts | {total} |")
    lines.append(f"| Local (ollama) | {local} ({local/total*100:.0f}%) |")
    lines.append(f"| Cloud | {cloud} ({cloud/total*100:.0f}%) |")
    lines.append(f"| Avg latency | {avg_latency:.0f}ms |")
    lines.append(f"| Total cost | ${total_cost:.4f} |")
    lines.append("")
    
    # By complexity
    by_complexity = {}
    for e in logs:
        c = e.get("complexity", "UNKNOWN")
        if c not in by_complexity:
            by_complexity[c] = []
        by_complexity[c].append(e)
    
    lines.append("## By Complexity Tier")
    lines.append(f"| Tier | Count | Local % | Avg Latency | Cost |")
    lines.append(f"|------|-------|---------|-------------|------|")
    for c in ["TRIVIAL", "SIMPLE", "MEDIUM", "HARD"]:
        if c in by_complexity:
            entries = by_complexity[c]
            local_count = sum(1 for e in entries if e.get("provider") == "ollama")
            avg_lat = sum(e.get("latency_ms", 0) for e in entries) / len(entries)
            cost = sum(e.get("cost", 0) for e in entries)
            lines.append(f"| {c} | {len(entries)} | {local_count/len(entries)*100:.0f}% | {avg_lat:.0f}ms | ${cost:.4f} |")
        else:
            lines.append(f"| {c} | 0 | - | - | - |")
    lines.append("")
    
    # By node
    by_node = {}
    for e in logs:
        n = e.get("node", "unknown")
        if n not in by_node:
            by_node[n] = []
        by_node[n].append(e)
    
    lines.append("## By Node")
    lines.append(f"| Node | Prompts | Models Used | Avg Latency |")
    lines.append(f"|------|---------|-------------|------------|")
    for node, entries in sorted(by_node.items(), key=lambda x: -len(x[1])):
        models = set(e.get("model", "unknown") for e in entries)
        avg_lat = sum(e.get("latency_ms", 0) for e in entries) / len(entries)
        lines.append(f"| {node} | {len(entries)} | {', '.join(models)} | {avg_lat:.0f}ms |")
    lines.append("")
    
    # Cloud escalations
    cloud_logs = [e for e in logs if e.get("provider") != "ollama"]
    if cloud_logs:
        lines.append("## Cloud Escalations")
        lines.append(f"| Prompt | Complexity | Model | Latency |")
        lines.append(f"|--------|------------|-------|---------|")
        for e in cloud_logs:
            lines.append(f"| {e.get('prompt_preview', '?')[:40]} | {e.get('complexity', '?')} | {e.get('model', '?')} | {e.get('latency_ms', 0)}ms |")
        lines.append("")
    
    lines.append("---")
    lines.append("Generated by routing_dashboard.py")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Weekly routing dashboard")
    parser.add_argument("--weekly", action="store_true", help="Show weekly report")
    parser.add_argument("--save", action="store_true", help="Save to wiki/status/")
    args = parser.parse_args()
    
    logs = load_logs(7)
    report = generate_report(logs)
    print(report)
    
    if args.save:
        STATUS_DIR.mkdir(parents=True, exist_ok=True)
        out_file = STATUS_DIR / f"ROUTING-DASHBOARD-{datetime.now().strftime('%Y-%m-%d')}.md"
        with open(out_file, 'w') as f:
            f.write(report)
        print(f"\nSaved to: {out_file}")


if __name__ == "__main__":
    main()
