---
# Default variables for DuckDNS updater

duckdns_domain: "carlos-lab"
duckdns_token: "YOUR_DUCKDNS_TOKEN_HERE"

duckdns_script_dir: "/usr/local/bin"
duckdns_cron_schedule: "*/5 * * * *"
duckdns_log_file: "/var/log/duckdns-update.log"

# Whether to suppress cron output (recommended: true)
duckdns_cron_suppress_output: true
